all:
  hosts:
    master-1:
      ansible_host: 192.168.4.26
      ip: 192.168.4.26
      access_ip: 192.168.4.26
    worker-1:
      ansible_host: 192.168.2.31  
      ip: 192.168.2.31  
      access_ip: 192.168.2.31
    worker-2:
      ansible_host: 192.168.3.31  
      ip: 192.168.3.31  
      access_ip: 192.168.3.31
    worker-3:
      ansible_host: 192.168.4.21  
      ip: 192.168.4.21  
      access_ip: 192.168.4.21
  children:
    kube_control_plane:
      hosts:
        master-1:
    kube_node:
      hosts:
        worker-1: 
        worker-2: 
        worker-3: 
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
